Blocks:
    '0': air
    '1': air
    '2': air
    '3': air
    '4': glass
    '5': air
    '6': air
    '7': air
    '8': air
    '9': air
    '10': glass
    '11': air
    '12': air
    '13': air
    '14': air
    '15': air
    '16': glass
    '17': air
    '18': glass
    '19': air
    '20': glass
    '21': air
    '22': air
    '23': air
    '24': glass
    '25': air
    '26': glass
    '27': air
    '28': glass
    '29': air
    '30': air
    '31': air
    '32': air
    '33': air
    '34': glass
    '35': air
    '36': air
    '37': air
    '38': air
    '39': air
    '40': glass
    '41': air
    '42': air
    '43': air
    '44': air
